spring:
      datasource:
                url: jdbc:postgresql://localhost:3306/ips
                username: admin
                password: admin
      jpa:
          hibernate:
                    ddl-auto: update
